# Generated by Django 4.0.5 on 2022-06-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeData',
            fields=[
                ('video_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=5100, null=True)),
                ('channel_id', models.CharField(max_length=500)),
                ('channel_title', models.CharField(blank=True, max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('published_datetime', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
            ],
        ),
    ]
